[tool.poetry]
name = "SANDI_python_toolbox"
version = "0.1.0"
description = "SANDI model fitting in python + BIDS handling"
authors = ["Bradley-Karat <bkarat@uwo.ca>"]
license = "BSD-2-Clause"
readme = "README.md"
packages = [{include = "SANDI_python_toolbox"}]

[tool.poetry.dependencies]
python = "^3.6"
snakebids = "^0.5.0"
snakemake = "^7.25.0"
numpy = "^1.24.2"
nibabel = "^5.1.0"
scipy = "^1.10.1"
scikit-image = "^0.19.3"
matplotlib = "^3.7.0"
scikit-learn = "^1.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
